"""What this business decided last time, rendered for a prompt.

Phase 2.4 made a tenant's own decisions findable. This is the part that
matters to a person: an approver looking at a collections escalation should
not have to remember for themselves that they approved one in September and
another in March. The agent has the record; it should say so.

Three things constrain how that record is used.

**The question is written in the same shape as the memories.** The embedding
model matches near-duplicates and little else (D25), so a free-form query
would miss memories that describe the same situation in different words. The
query is therefore `history.describe()` of the decision being explained —
generated by the identical template that produced everything in the store. The
two texts are made to rhyme on purpose.

**Only standouts are quoted.** `worth_quoting` drops anything not measurably
closer than the tenant's other memories. That is strict enough to stay silent
often, and it should be: a business quoted an irrelevant precedent with
confidence will believe it, and the cost of that is higher than the cost of
saying nothing.

One consequence is worth stating plainly rather than discovering later.
`standout` needs something to compare against, so a tenant with a single prior
decision gets nothing quoted, however apt it is. That is the honest answer —
with one candidate there is no evidence it is relevant — but it means this
feature stays quiet for a business's first months and only becomes useful once
there is a history to be a standout *within*.

**Nothing is claimed about consequences.** Whether acting helped is not
tracked anywhere yet (Phase 9), so the instructions forbid the model from
asserting it. A recalled decision is what this business chose, not proof it
chose correctly, and an explanation that blurred those would be inventing the
most persuasive part of itself.
"""

from __future__ import annotations

import logging
import uuid

from aether.core.models import PendingApproval
from aether.knowledge import history, retrieval
from aether.knowledge.retrieval import Recollection

logger = logging.getLogger(__name__)

# Wide enough that "closer than the rest" is a real comparison — the median in
# `standout` is meaningless over two or three candidates — and narrow enough
# that the extra rows cost nothing, since only standouts are ever rendered.
_CANDIDATES = 8


def prior_decisions(
    tenant_id: uuid.UUID, approval: PendingApproval, *, limit: int = _CANDIDATES
) -> list[Recollection]:
    """This business's own past decisions that resemble the one at hand.

    Restricted to what happened before this decision, and never to this
    decision itself. Both matter: a backfill indexes pending approvals too, so
    without them the nearest memory to a decision is reliably that same
    decision, quoted back to the approver as precedent for itself.
    """
    return retrieval.worth_quoting(
        tenant_id,
        history.describe(approval),
        limit=limit,
        kind=history.KIND_DECISION,
        before=approval.created_at,
        exclude_source_id=approval.id,
    )


def context_block(recollections: list[Recollection]) -> str:
    """The recalled decisions as prompt text, or "" when there are none."""
    if not recollections:
        return ""

    lines = [
        "This business has faced something comparable before. The following are "
        "its own past decisions, recalled from its records — not general advice, "
        "and not evidence about what will happen this time:"
    ]
    lines.extend(f"- {r.body}" for r in recollections)
    return "\n".join(lines) + "\n\n"


def extra_instructions(recollections: list[Recollection]) -> str:
    """How the explanation must treat what was recalled."""
    if not recollections:
        return ""
    return (
        "Where a past decision above is genuinely relevant, mention it: say when "
        "it happened and what was decided, so the approver is reminded rather "
        "than left to remember. Do NOT say or imply that any of them worked, "
        "helped, fixed anything, or caused what followed — the outcome of a past "
        "decision is not recorded, and asserting one would be an invention. If a "
        "recalled decision does not fit this situation, leave it out entirely.\n"
    )


def for_approval(tenant_id: uuid.UUID, approval: PendingApproval) -> tuple[str, str]:
    """Instructions and context for one decision, as `(instructions, context)`.

    Never raises. Memory is an enhancement to an explanation and never a
    precondition for one, so a knowledge base that is down, empty or holding
    nothing relevant costs the approver a sentence, not the diagnosis.
    """
    try:
        found = prior_decisions(tenant_id, approval)
    except Exception:  # noqa: BLE001 - see the docstring
        logger.warning("prior decisions unavailable for %s", tenant_id, exc_info=True)
        return "", ""
    return extra_instructions(found), context_block(found)
